// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiCDB.Data;

namespace WebApiCDB.Migrations
{
    [DbContext(typeof(WebApiCDBContext))]
    partial class WebApiCDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiCDB.Models.BankUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<double?>("Balance")
                        .HasColumnType("float");

                    b.Property<string>("ConfirmPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DoB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Mobile")
                        .HasColumnType("bigint");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PinCode")
                        .HasColumnType("int");

                    b.Property<string>("SAns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sques")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BankUser");
                });

            modelBuilder.Entity("WebApiCDB.Models.FD", b =>
                {
                    b.Property<int>("FdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BankUsersId")
                        .HasColumnType("int");

                    b.Property<double>("FdInMoney")
                        .HasColumnType("float");

                    b.Property<double>("FdInvMon")
                        .HasColumnType("float");

                    b.Property<double>("FdMAmount")
                        .HasColumnType("float");

                    b.Property<double>("Month")
                        .HasColumnType("float");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("n")
                        .HasColumnType("int");

                    b.HasKey("FdId");

                    b.HasIndex("BankUsersId");

                    b.ToTable("FD");
                });

            modelBuilder.Entity("WebApiCDB.Models.RD", b =>
                {
                    b.Property<int>("RdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BankUserId")
                        .HasColumnType("int");

                    b.Property<double>("FdInMoney")
                        .HasColumnType("float");

                    b.Property<double>("FdMatureAmount")
                        .HasColumnType("float");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<double>("RdInvMon")
                        .HasColumnType("float");

                    b.Property<double>("Time")
                        .HasColumnType("float");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("n")
                        .HasColumnType("int");

                    b.HasKey("RdId");

                    b.HasIndex("BankUserId");

                    b.ToTable("RD");
                });

            modelBuilder.Entity("WebApiCDB.Models.FD", b =>
                {
                    b.HasOne("WebApiCDB.Models.BankUser", "BankUsers")
                        .WithMany()
                        .HasForeignKey("BankUsersId");

                    b.Navigation("BankUsers");
                });

            modelBuilder.Entity("WebApiCDB.Models.RD", b =>
                {
                    b.HasOne("WebApiCDB.Models.BankUser", "BankUser")
                        .WithMany()
                        .HasForeignKey("BankUserId");

                    b.Navigation("BankUser");
                });
#pragma warning restore 612, 618
        }
    }
}
